homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
#Anpassungen
  customize: !include customize.yaml
#DB Config
recorder:
  db_url: mysql://hass:6z7JRFGwCpP1r5w8@core-mariadb/homeassistant
  purge_keep_days: 3
#Übersicht Geräte
map:
#Hass IO
hassio:
#Discovery komponente
discovery:
  ignore:
    - igd
#  enable:
#    - homekit
#Zonen
zone:
 - name: Home
   latitude: !secret zone_home_latitude
   longitude: !secret zone_home_longitude
   radius: !secret zone_home_radius
#Caro
 - name: !secret zone_caro_name
   latitude: !secret zone_caro_latitude
   longitude: !secret zone_caro_longitude
   radius: !secret zone_caro_radius
#Robin
 - name: !secret zone_robin_name
   latitude: !secret zone_robin_latitude
   longitude: !secret zone_robin_longitude
   radius: !secret zone_robin_radius
#Haus
 - name: !secret zone_haus_name
   latitude: !secret zone_haus_latitude
   longitude: !secret zone_haus_longitude
   radius: !secret zone_haus_radius
#Verlauf der Geräte
history:
  exclude:
    entities:
      - light.flur
      - input_slider.ventilator_slider
      - light.schlafzimmer
      - light.sofa_wohnzimmer
      - light.wohnzimmer_raum
      - switch.ventilator_licht
      - switch.ventilator_stufe_1
      - switch.ventilator_stufe_2
      - switch.ventilator_stufe_4
      - sensor.pihole_dns_queries_today
      - sensor.pihole_ads_blocked_today
      - sensor.pihole_ads_percentage_today
      - sensor.pihole_ads_percentage_blocked_today
      - input_boolean.motion
      - input_boolean.motion_disabled
      - input_select.hyperion_effect
      - sensor.iphone_battery_state
      - sensor.iphone_von_carolin_battery_state
      - sensor.memory_free
      - sensor.pihole_ads_blocked_today
      - sensor.pihole_ads_percentage_blocked_today
      - sensor.pihole_dns_queries_today
      - light.entertainmentbereich_1
      - input_boolean.motion_flur
      - input_number.ventilator_slider
      - light.sofagruppe
      - light.wohnzimmer
      - remote.wohnzimmerhub
      - switch.krimmer_status
      - switch.pihole_switch
      - sensor.working_time_caro
      - sensor.working_time_robin
      - sensor.working_time_format_robin
      - sensor.working_time_format_caro
    domains:
      - automation
      - script
      - updater
      - group
logbook:
  exclude:
    entities:
      - light.flur
      - input_slider.ventilator_slider
      - light.schlafzimmer
      - light.sofa_wohnzimmer
      - light.wohnzimmer_raum
      - switch.ventilator_licht
      - switch.ventilator_stufe_1
      - switch.ventilator_stufe_2
      - switch.ventilator_stufe_4
      - sensor.pihole_dns_queries_today
      - sensor.pihole_ads_blocked_today
      - sensor.pihole_ads_percentage_today
      - sensor.pihole_ads_percentage_blocked_today
      - input_boolean.motion
      - input_boolean.motion_disabled
      - input_select.hyperion_effect
      - sensor.flur_lux
      - sensor.flur_temperatur
      - sensor.iphone_battery_level
      - sensor.iphone_battery_state
      - sensor.iphone_von_carolin_battery_level
      - sensor.iphone_von_carolin_battery_state
      - sensor.memory_free
      - sensor.pihole_ads_blocked_today
      - sensor.pihole_ads_percentage_blocked_today
      - sensor.pihole_dns_queries_today
      - sensor.processor_use
      - sensor.wohnzimmer_lux
      - sensor.wohnzimmer_temperatur
      - light.entertainmentbereich_1
      - input_boolean.motion_flur
      - input_number.ventilator_slider
      - light.sofagruppe
      - light.wohnzimmer
      - remote.wohnzimmerhub
      - switch.krimmer_status
      - switch.pihole_switch
      - sensor.working_time_caro
      - sensor.working_time_robin
      - sensor.working_time_format_robin
      - sensor.working_time_format_caro
    domains:
      - automation
      - script
      - updater
      - group
http:
  # Uncomment this to add a password (recommended!)
 api_password: !secret http_password
 cors_allowed_origins:
   - http://192.168.1.15:7080
 server_port: 8123
 base_url: http://192.168.1.15:8123
 ip_ban_enabled: True
 login_attempts_threshold: 3
config:
####################################################
#                                                  #
#                     Includes                     #
#                                                  #
####################################################
media_player: !include media_players.yaml
device_tracker: !include device_trackers.yaml
notify: !include notify.yaml
switch: !include switches.yaml
automation: !include_dir_merge_list automation/
scene: !include scenes.yaml
group: !include groups.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
input_select: !include input_select.yaml
shell_command: !include shell_commands.yaml
binary_sensor: !include binary_sensor.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
fan: !include fan.yaml
####################################################
#                                                  #
#                     Enables                      #
#                                                  #
####################################################
# Pilight connection
pilight:
  host: 192.168.1.20
  port: 5000
#Datenbank
# Enables support for tracking state changes over time.
#logger:
#  default: critical
#Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/
  #javascript_version: latest
#Bindet die iPhone APP ein.
ios:
#MQTT Broker
mqtt:
  broker: 192.168.1.15
  port: 8882
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'
  username: !secret mqtt_username
  password: !secret mqtt_password
#MDI
panel_iframe:
  mdiindex:
    title: MDI Icon Index
    icon: mdi:vector-square
    url: https://cdn.rawgit.com/james-fry/home-assistant-mdi/efd95d7a/home-assistant-mdi.html
#Alexa
cloud:
  alexa:
    filter:
      include_entities:
        - switch.steckdose
        - script.ventilator_timer_stufe_1
        - switch.garten2
        - script.timed_nachtlicht
        - input_boolean.motion_disabled
        - switch.krimmer_kerzen
        - media_player.yamahaav
        - light.decke
        - light.esstisch
        - light.gitarre
        - light.nachtisch_caro
        - light.nachtisch_robin
        - light.sofa
        - light.stehlampe
        - switch.ventilator_licht
        - script.party_hue
        - media_player.anlage
    entity_config:
      input_boolean.motion_disabled:
        display_categories: LIGHT
      switch.steckdose:
        display_categories: LIGHT
      switch.ventilator_licht:
        display_categories: LIGHT
#emulated_hue:
#  host_ip: 192.168.1.15
#  type: google_home
#  listen_port: 8300
#  off_maps_to_on_domains:
#    - script
#    - scene
#  expose_by_default: false
#  entities:
#    light.steckdose:
#      hidden: false
#    script.ventilator_timer_stufe_1:
#      hidden: false
#    switch.garten2:
#      hidden: false
#    script.timed_nachtlicht:
#      hidden: false
#    input_boolean.motion_disabled:
#      hidden: false
#    switch.krimmer_kerzen:
#      hidden: false
#    light.decke:
#      hidden: false
#    light.esstisch:
#      hidden: false
#    light.gitarre:
#      hidden: false
#    light.nachtisch_caro:
#      hidden: false
#    light.nachtisch_robin:
#      hidden: false
#    light.sofa:
#      hidden: false
#    light.stehlampe:
#      hidden: false
#    switch.ventilator_licht:
#      hidden: false
#    script.party_hue:
#      hidden: false
#    switch.garten1:
#      hidden: false
#Harmony HUB
remote:
  - platform: harmony
    name: Wohnzimmer-Hub
    host: 192.168.1.30
    activity: PowerOff
#hue:
#  bridges:
#    - host: 192.168.1.31
#      filename: phue.conf
#  - platform: hyperion
#    host: 192.168.1.142
timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 600 # Updated this to the number of seconds you wish
