#- platform: nmap_tracker
 # hosts:
  #  - 192.168.1.164
  #home_interval: 10
# - platform: fritz
  # host: 192.168.1.1
  # track_new_devices: False
  # consider_home: 300
# - platform: fritz
  # host: 192.168.1.50
  # track_new_devices: False
  # consider_home: 300

- platform: owntracks
  max_gps_accuracy: 100
  waypoints: false
  events_only: false