- platform: template
  fans:
    schlafzimmer_fan:
      friendly_name: "Schlafzimmer Ventilator"
      value_template: "{{ states('switch.fan_bedroom_status')}}"
      turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.ventilator_licht
        - service: switch.turn_on
          data:
            entity_id: switch.fan_bedroom_status     
      turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.ventilator_licht
        - service: switch.turn_off
          data:
            entity_id: switch.fan_bedroom_status    
      set_speed:
        service: scene.turn_on
        data_template:
          entity_id: >
            {% if speeds == '3' %}
              scene.ventilator_stufe_3
            {% elif speeds == '2' %}
              scene.ventilator_stufe_2
            {% elif speeds == '1' %}
              scene.ventilator_stufe_1
            {% else %}
            {% endif %}
      speeds:
        - '1'
        - '2'
        - '3'