#AV-Receiver
- platform: yamaha
  host: 192.168.1.32
  name: Yamaha-AV
  source_ignore:
    - "AUX"
    - "HDMI6"
    - "HDMI5"
    - "HDMI4"
    - "AV1"
    - "AV2"
    - "AV3"
    - "AV1"
    - "AV5"
    - "AV6"
    - "AUDIO"
    - "TUNER"
    - "V-AUX"
    - "iPod (USB)"
    - "USB"
  source_names:
    HDMI1: "FireTV"
    HDMI2: "PS4"
    HDMI3: "GCast"
    AV4: "AV4"
#Sonos
#- platform: sonos

#- platform: cast

- platform: spotify
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

#- platform: firetv



#Kodi
#- platform: kodi
 # host: http://192.168.0.142

- platform: panasonic_viera
  host: 192.168.1.35
  name: TV
